import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbarItem = [
  { title: "Home", route: "/home" },
  { title: "Careers", route: "/careers" },
  { title: "Our Team", route: "/our-team" },
  { title: "Contact Us", route: "/contact-us" },
  { title: "Sign Up Guide", route: "/signup-guide" },
  { title: "Explore Now", route: "/explore" },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <navbar className="flex justify-between items-center fixed  w-full px-[120px] py-5">
          <div>
            <Image src={"/images/logo.png"} alt="" height={35} width={196} />
          </div>
          <div className="flex justify-center items-center gap-6">
            {navbarItem?.map((item, index) => (
              <div
                key={index}
                className={
                  item?.title === "Explore Now"
                    ? "bg-white text-[#038175] px-5 py-2 text-[18px] rounded-full"
                    : "text-white text-[18px]"
                }
              >
                {item?.title}
              </div>
            ))}
          </div>
        </navbar>
        <div>{children}</div>
        <footer></footer>
      </body>
    </html>
  );
}
